pytorch의 가장 핵심적인 개념 tensor
- n차원의 matrix임. pytorch에서는 tensor를 이용해 모델의 입출력과 매개변수들을 부호화(encode)함.
- numpy와 유사한 자료구조
- 다만 numpy가 제공하지 않은 연산그래프, 딥러닝, 변화도 같은 프레임워크 기능을 가짐
- gpu를 활용하여 연산 가속화 가능

In [31]:
import torch # jupyter 환경 우측상단에서 바꿔줘야함 kotorch 가상환경으로
import numpy as np

### 1. 텐서 초기화

In [32]:
# 데이터로부터 직접 텐서 생성
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [33]:
# ndarray로부터 텐서 생성
ndarray = np.array(data)
x_np = torch.from_numpy(ndarray)

In [34]:
# 텐서로부터 텐서 생성 (자료형, 크기 유지)
## ones : 1로 생성
x_ones = torch.ones_like(x_data)
print(x_ones)
## rand : random값으로 생성
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.7791, 0.4634],
        [0.0869, 0.3884]])


In [35]:
# 무작위 or 상수 값 사용하기
## shape : 텐서의 차원을 나타내는 튜플
shape = (2,3,) # 끝에 ,는 튜플임을 나타내기 위해 관행적으로..
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6760, 0.9887, 0.6985],
        [0.9831, 0.2644, 0.5456]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 2. 텐서의 속성
- 속성은 shape, datatype, 저장 장치 위치

In [36]:
tensor = torch.rand(3,4) # 3,4 사이즈의 0~1 랜덤값 배열의 텐서
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### 3. 텐서 연산

In [37]:
tensor = torch.rand(4,4)
tensor

tensor([[0.0893, 0.6299, 0.5055, 0.8546],
        [0.8329, 0.8501, 0.3826, 0.2501],
        [0.2242, 0.8027, 0.5568, 0.5139],
        [0.7821, 0.2610, 0.1561, 0.9239]])

In [38]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
tensor[:,1] = 0 # 이렇게 값 변경도 가능
print(tensor)

First row: tensor([0.0893, 0.6299, 0.5055, 0.8546])
First column: tensor([0.0893, 0.8329, 0.2242, 0.7821])
Last column: tensor([0.8546, 0.2501, 0.5139, 0.9239])
tensor([[0.0893, 0.0000, 0.5055, 0.8546],
        [0.8329, 0.0000, 0.3826, 0.2501],
        [0.2242, 0.0000, 0.5568, 0.5139],
        [0.7821, 0.0000, 0.1561, 0.9239]])


In [39]:
t1= torch.cat([tensor, tensor, tensor], dim=1) # concat 함수임, dim은 방향
print(t1.shape,'\n')
t1

torch.Size([4, 12]) 



tensor([[0.0893, 0.0000, 0.5055, 0.8546, 0.0893, 0.0000, 0.5055, 0.8546, 0.0893,
         0.0000, 0.5055, 0.8546],
        [0.8329, 0.0000, 0.3826, 0.2501, 0.8329, 0.0000, 0.3826, 0.2501, 0.8329,
         0.0000, 0.3826, 0.2501],
        [0.2242, 0.0000, 0.5568, 0.5139, 0.2242, 0.0000, 0.5568, 0.5139, 0.2242,
         0.0000, 0.5568, 0.5139],
        [0.7821, 0.0000, 0.1561, 0.9239, 0.7821, 0.0000, 0.1561, 0.9239, 0.7821,
         0.0000, 0.1561, 0.9239]])

#### 산술 연산

In [43]:
data = [[1,2],[3,4]]
data2 = [[2,3],[4,5]]
t1 = torch.tensor(data)
t2 = torch.tensor(data2)
print(t1,'\n',t2)

tensor([[1, 2],
        [3, 4]]) 
 tensor([[2, 3],
        [4, 5]])


In [46]:
# 같은표현임 : 행렬 곱
print(torch.matmul(t1,t2))
print(t1 @ t2)

tensor([[10, 13],
        [22, 29]])
tensor([[10, 13],
        [22, 29]])


In [45]:
# 같은표현임 : 요소별 곱(내적)
print(torch.mul(t1,t2))
print(t1 * t2)

tensor([[ 2,  6],
        [12, 20]])
tensor([[ 2,  6],
        [12, 20]])
