### Vector, Matrix, Tensor
- Vector : 그냥 리스트. "직선" [가 1개
- Matrix : m*n의 "직사각형" [[ 2개
    - [1,2,3] : 그냥 직선개념임.
    - [[1,2,3]] : 1행3열짜리 매트릭스. 세로값이 1인 직사각형이 되어버린다
- Tensor : b*m*n "직육면체" [[[ 3개
    - .으로 나오는건 실수형이라서 그렇다
    - LongTensor하면 정수로 되서 .안나옴

### View
- numpy의 reshape이랑 같음
- -1을 쓰면, 그 부분은 자동연산하고 나머지에 입력한 대로 shape을 맞추라는 뜻!

In [1]:
import numpy as np
import torch

ndarray = np.array([[[0,1,2],
                     [3,4,5]],
                    
                    [[6,7,8],
                     [9,10,11]]])

tensor = torch.FloatTensor(ndarray)

tensor.shape

torch.Size([2, 2, 3])

- (2행,3열로 된 매트릭스가) batch로 2개

In [2]:
print(tensor.view([-1,3])) # 3열로 무조건 맞추고 앞에는 12/3 = 4됨
print(tensor.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


- 배치사이즈없이 그냥 (4행 3열짜리 매트릭스가) 되었음!

In [3]:
print(tensor.view([-1,1,3])) # 1행 3열로 무조건 맞추고 앞에는 12/(3*1) = 4배치
print(tensor.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


- (1행 3열짜리로 된 매트릭스)가 4개!!

### Squeeze & Unsqueeze
- Sqeeze : dim 중에 값이 1인애를 짜서 없애준다
- Unsqeeze : 입력한 dim에 1을 만들어준다

#### Squeeze

In [4]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape) # 3행 1열짜리 매트릭스가 1개

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [7]:
print(ft.squeeze())
print(ft.squeeze().shape) # 3행1열 매트릭스 => 그냥 3개짜리 벡터가 됨

tensor([0., 1., 2.])
torch.Size([3])


#### Unsqueeze

In [8]:
ft = torch.Tensor([0,1,2])
ft.shape

torch.Size([3])

In [9]:
print(ft.unsqueeze(0)) # 0번째에 차원에 1값을 넣어준다
print(ft.unsqueeze(0).shape) # 그냥 3개짜리 벡터가 1행3열짜리 매트릭스가 됨

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [10]:
print(ft.unsqueeze(1)) # [1,3] => 1번째를 1로 만든다 = > [?,1] : 3/1 => ?=3
print(ft.unsqueeze(1).shape) # 즉 3행1열짜리 매트릭스가 되어버림
# unsqeeze(-1) 도 여기서는 (1)이랑 의미가 같아짐. 맨 마지막이 결국 1번째니까

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Cat(Concatenate)

In [11]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]]) # 2,2 짜리 사각형

In [13]:
print(torch.cat([x,y], dim=0)) # 0번째차원. 즉 행으로 붙여라
print(torch.cat([x,y], dim=1)) # 1번째차원. 즉 열로 붙여라

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
