### 1. 데이터 로드

In [19]:
import pandas as pd

path = r'C:\Users\SeoJeongBin\Desktop\Code\Team_project_gawon\data\train.csv'
df = pd.read_csv(path)
df = df.iloc[:,1:]
df

X_01     X_02   X_03  X_04     X_05    X_06   X_07    X_08    X_09  \
0      70.544  103.320  67.47     1  101.892  74.983  29.45   62.38  245.71   
1      69.524  103.321  65.17     1  101.944  72.943  28.73   61.23  233.61   
2      72.583  103.320  64.07     1  103.153  72.943  28.81  105.77  272.20   
3      71.563  103.320  67.57     1  101.971  77.022  28.92  115.21  255.36   
4      69.524  103.320  63.57     1  101.981  70.904  29.68  103.38  241.46   
...       ...      ...    ...   ...      ...     ...    ...     ...     ...   
39602  66.465  103.320  62.27     1  103.150  66.825  30.20   77.83  298.05   
39603  66.465  103.321  62.77     1  102.021  66.825  29.21  102.25  270.67   
39604  68.504  103.320  64.67     1  103.144  68.864  29.96  102.61  198.07   
39605  66.465  103.320  63.67     1  102.025  67.845  30.30  112.60  275.52   
39606  66.465  103.320  65.67     1  102.004  69.884  30.16  112.90  276.06   

       X_10  ...    Y_05    Y_06   Y_07    Y_08    Y_09    Y_10    Y_11  \
0       0.0  ...  29.632  16.083  4.276 -25.381 -25.529 -22.769  23.792   
1       0.0  ...  33.179  16.736  3.229 -26.619 -26.523 -22.574  24.691   
2       0.0  ...  31.801  17.080  2.839 -26.238 -26.216 -22.169  24.649   
3       0.0  ...  34.503  17.143  3.144 -25.426 -25.079 -21.765  24.913   
4       0.0  ...  32.602  17.569  3.138 -25.376 -25.242 -21.072  25.299   
...     ...  ...     ...     ...    ...     ...     ...     ...     ...   
39602   0.0  ...  29.194  16.582  3.410 -26.486 -26.581 -22.772  24.261   
39603   0.0  ...  29.859  15.659  3.406 -27.308 -27.203 -24.674  23.427   
39604   0.0  ...  24.720  16.823  3.215 -26.502 -26.687 -22.577  24.301   
39605   0.0  ...  26.412  15.757  4.216 -26.760 -26.634 -24.066  23.305   
39606   0.0  ...  30.745  16.781  3.307 -26.054 -26.251 -23.257  24.450   

         Y_12    Y_13    Y_14  
0     -25.470 -25.409 -25.304  
1     -26.253 -26.497 -26.438  
2     -26.285 -26.215 -26.370  
3     -25.254 -25.021 -25.345  
4     -25.072 -25.195 -24.974  
...       ...     ...     ...  
39602 -26.491 -26.584 -26.580  
39603 -27.250 -27.334 -27.325  
39604 -26.388 -26.425 -26.601  
39605 -26.536 -26.751 -26.635  
39606 -26.224 -26.256 -26.093  

[39607 rows x 70 columns]

### 2. 전처리

#### 2-1. 이상한 값 제거

In [20]:
df.isnull().sum()

X_01    0
X_02    0
X_03    0
X_04    0
X_05    0
       ..
Y_10    0
Y_11    0
Y_12    0
Y_13    0
Y_14    0
Length: 70, dtype: int64

In [21]:
x_columns = df.columns[:56]
for col in x_columns:
    if len(df[col].unique()) == 1:
        print(col)
        df = df.drop([col], axis=1)
df.head(3)

X_04
X_23
X_47
X_48


X_01     X_02   X_03     X_05    X_06   X_07    X_08    X_09  X_10  X_11  \
0  70.544  103.320  67.47  101.892  74.983  29.45   62.38  245.71   0.0   0.0   
1  69.524  103.321  65.17  101.944  72.943  28.73   61.23  233.61   0.0   0.0   
2  72.583  103.320  64.07  103.153  72.943  28.81  105.77  272.20   0.0   0.0   

   ...    Y_05    Y_06   Y_07    Y_08    Y_09    Y_10    Y_11    Y_12    Y_13  \
0  ...  29.632  16.083  4.276 -25.381 -25.529 -22.769  23.792 -25.470 -25.409   
1  ...  33.179  16.736  3.229 -26.619 -26.523 -22.574  24.691 -26.253 -26.497   
2  ...  31.801  17.080  2.839 -26.238 -26.216 -22.169  24.649 -26.285 -26.215   

     Y_14  
0 -25.304  
1 -26.438  
2 -26.370  

[3 rows x 66 columns]

In [22]:
print(df['X_10'].value_counts())
print(df['X_11'].value_counts())

0.0    39575
2.9       12
3.0       12
3.3        4
3.1        2
3.6        1
3.2        1
Name: X_10, dtype: int64
0.0    39580
0.5       12
0.6       11
0.4        3
0.7        1
Name: X_11, dtype: int64


In [23]:
df = df.drop(['X_10','X_11','X_46'], axis=1)

#### 2-2. 이상치 제거

In [24]:
# IQR 기반 이상치 제거
# dl 은 데이터 많으면 이상치 제거안해도 알아서 그거까지 잘 학습하는 식인듯.

### 3. 학습 데이터 분할

In [25]:
x = df.iloc[:, :-14]
y = df.iloc[:, -14:]

In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

x_train # df

X_01     X_02   X_03     X_05    X_06   X_07     X_08    X_09  X_12  \
37287  70.544  103.320  65.17  103.150  70.904  31.77   222.29  270.78  4.38   
2173   72.583  103.320  67.57  103.151  72.943  30.46    72.39  251.76  4.38   
3609   72.583  103.321  74.27  101.947  72.943  33.77  1381.34   37.58  4.38   
3027   66.465  103.320  68.57  102.005  66.825  25.59   109.78  179.77  4.37   
31350  64.425  103.320  77.57  102.045  66.825  26.73    74.46  255.90  4.38   
...       ...      ...    ...      ...     ...    ...      ...     ...   ...   
6265   69.524  103.320  71.97  101.870  70.904  48.24   120.52  608.69  4.34   
11284  68.504  103.320  71.67  101.935  72.943  30.90   119.81  268.32  4.38   
38158  71.563  103.320  66.77  103.156  71.923  28.67  2362.16   37.58  4.38   
860    68.504  103.320  70.67  101.966  68.864  29.44   232.11  200.89  4.38   
15795  67.485  103.320  64.67  102.013  68.864  27.70   167.47  295.50  4.35   

       X_13  ...   X_44  X_45      X_49        X_50        X_51        X_52  \
37287  0.15  ...  21.18  0.17  14210.43  132.984753  132.917286  140.042024   
2173   0.13  ...  21.22  0.11  14159.23  137.039670  131.469418  145.135217   
3609   0.14  ...  21.14  0.24  23228.33  122.577565  121.785160  125.584215   
3027   0.17  ...  21.11  0.19  11903.93  121.535229  128.199551  127.536043   
31350  0.14  ...  21.10  0.16  16919.83  151.019604  148.448589  136.757616   
...     ...  ...    ...   ...       ...         ...         ...         ...   
6265   0.15  ...  21.09  0.19  15585.73  124.925084  124.813091  123.314043   
11284  0.09  ...  21.08  0.13  14228.73  126.370267  130.973187  135.857515   
38158  0.14  ...  21.20  0.13  12088.23  137.139912  134.100041  147.350031   
860    0.20  ...  21.15  0.20  19974.53  130.648595  127.940746  135.476869   
15795  0.14  ...  21.12  0.18  17411.03  129.951794  147.583119  143.455698   

             X_53        X_54        X_55        X_56  
37287  130.635954  126.664081  134.437619  131.312313  
2173   131.541037  131.482426  129.437153  135.319843  
3609   115.501127  126.467319  127.597096  125.188778  
3027   124.847639  129.571697  132.293324  130.435955  
31350  135.160307  131.352207  138.953572  130.342182  
...           ...         ...         ...         ...  
6265   116.561773  119.467594  122.416775  123.261044  
11284  133.020071  132.835186  130.027691  126.445255  
38158  130.241667  134.185695  147.163205  133.407581  
860    124.291716  122.022510  128.166859  124.283352  
15795  132.143484  130.631039  148.609951  127.784481  

[27724 rows x 49 columns]

In [27]:
from sklearn.preprocessing import MinMaxScaler

x_scaler = MinMaxScaler()
y_scaler = MinMaxScaler() # x,y 따로 나누는 이유는 혹시나 실제 y값을 print할때 찌부된거 복원시키기 위함

x_train = x_scaler.fit_transform(x_train)
x_test = x_scaler.transform(x_test)
y_train = x_scaler.fit_transform(y_train)
y_test = x_scaler.transform(y_test)

x_train
# ndarray (df아님)
# ml이든 dl이든 학습돌릴때도 df가 아니라 값이여야함. df면 .values하거나 ndarray로 바꿔줘야

array([[0.5       , 0.        , 0.26605505, ..., 0.68520005, 0.76514467,
        0.84000076],
       [0.57141356, 0.        , 0.33944954, ..., 0.71654645, 0.73081701,
        0.87063095],
       [0.57141356, 1.        , 0.54434251, ..., 0.68391999, 0.71818521,
        0.79319762],
       ...,
       [0.53568927, 0.        , 0.31498471, ..., 0.73413293, 0.85250446,
        0.85601523],
       [0.42855141, 0.        , 0.43425076, ..., 0.65500368, 0.72209657,
        0.7862773 ],
       [0.39286215, 0.        , 0.25076453, ..., 0.71100763, 0.86243622,
        0.81303699]])

### 4. pytorch - Build Dataset

In [28]:
import torch
from torch.utils.data import Dataset, DataLoader

class MyDataset(Dataset):
    # 1) 전처리 (ndaaray => tensor)
    def __init__(self, x, y) :
        super().__init__()
        # input이 df면 .values, ndarray면 생략
        self.x = torch.FloatTensor(x)
        self.y = torch.FloatTensor(y)
    
    # 2) len() 했을때 개수반환 해주는 역할    
    def __len__(self):
        return len(self.x)
    
    # 3) dataset[i] 했을때 i번째 데이터 호출됨
    def __getitem__(self, index) :
        return self.x[index], self.y[index]
    
train_dataset = MyDataset(x_train, y_train)
test_dataset = MyDataset(x_test, y_test)

In [29]:
print(f'train_dataset 개수 : {len(train_dataset)}개')

train_dataset[0] # (0번째 x train의 torch, 0번째 y train의 torch)

train_dataset 개수 : 27724개


(tensor([0.5000, 0.0000, 0.2661, 0.9928, 0.3913, 0.0592, 0.0783, 0.3887, 0.5000,
         0.4348, 0.6765, 0.5926, 0.6286, 0.6316, 0.6667, 0.3933, 0.4167, 0.2706,
         0.3723, 0.3939, 0.3611, 0.3514, 0.3889, 0.4524, 0.5588, 0.5325, 0.1437,
         0.5130, 0.1306, 0.2083, 0.4286, 0.5833, 0.4444, 0.1053, 0.1066, 0.5034,
         0.5393, 0.4603, 0.7544, 0.6316, 0.4211, 0.0977, 0.8230, 0.7992, 0.8127,
         0.8397, 0.6852, 0.7651, 0.8400]),
 tensor([0.3150, 0.2273, 0.2648, 0.4034, 0.6757, 0.9396, 0.5767, 0.5497, 0.5469,
         0.8069, 0.6494, 0.4933, 0.5411, 0.5658]))

### 5. pytorch - Model

#### 5-1. 모델 클래스 짜기

In [30]:
import torch.nn as nn

class myMLP(nn.Module):
    def __init__(self, input_size, output_size, drop_ratio) :
        super(myMLP, self).__init__()
        # self.input_size = input_size => 이런거 다른 함수에서 사용하는 경우라면 self.로 받는거다
        self.layer_mlp = nn.Sequential(
            nn.Linear(input_size, 18),
            torch.nn.BatchNorm1d(18), # 배치정규화
            nn.Linear(18, 9),
            torch.nn.BatchNorm1d(9),
            nn.Linear(9, output_size),
            torch.nn.ReLU()
        )
        self.layer_dropout = torch.nn.Dropout(p=drop_ratio)
        self.layer_softmax = torch.nn.Softmax()
        
    def forward(self, x):
        output = self.layer_mlp(x)
        output = self.layer_dropout(output)
        output = self.layer_softmax(output)
        return output

#### 5-2. Dataloader => test dataloader는 shuffle False 해야하는듯?
- batch size 설정가능
- iterable한 객체로 감쌀 수 있음

In [31]:
train_dataloader = DataLoader(train_dataset, batch_size=768, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=768, shuffle=True)

In [32]:
loader = iter(train_dataloader)
x, y = next(loader) # 첫번째 batch가 나오는거임 이렇게하면
print(x.shape)
print(y.shape)

torch.Size([768, 49])
torch.Size([768, 14])


In [33]:
len(train_dataloader) # 총 사이즈 / batch_size 인듯

37

### 5-3. 모델 객체 선언 & optimizer 정의

In [34]:
loader = iter(train_dataloader)
x, y = next(loader) # 개수 입력해줄 용도로..

input_size = x.shape[1] # 입력변수 개수(칼럼 개수)
output_size = y.shape[1] # 예측변수 개수(칼럼 개수)
drop_ratio = 0.8

model = myMLP(input_size, output_size, drop_ratio)

In [35]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.MSELoss()

### 6. 학습

In [36]:
from tqdm import tqdm
epoch_num = 500

for epoch in tqdm(range(epoch_num)):
    # train mode
    model.train()
    train_loss = 0
    
    for x, y in train_dataloader :
        # x,y = x.to("cuda"), y.to("cuda")
        optimizer.zero_grad()
        pred = model(x)
        loss = loss_fn(pred, y)
        train_loss += loss.item() # 여기서 data loader 길이만큼 += 되니까 출력으로 볼때는 길이로 나눠줘야 함 당연히!
        loss.backward()
        optimizer.step()
    
    if epoch % 50 == 0 : # 100 배수의 epoch 마다 학습된 파라미터로 테스트 셋 평가해봄 
        # eval mode
        model.eval()
        val_loss = 0
        with torch.no_grad() : # test set은 학습없으니 역전파 없다
            for x,y in test_dataloader:
                # x,y = x.to("cuda"), y.to("cuda")
                pred = model(x)
                loss = loss_fn(pred, y)
                val_loss += loss.item()
                
        print(f'[Epoch : {epoch+1}/{epoch_num}] [train_loss : {train_loss/len(train_dataloader)}] [val_loss : {val_loss/len(test_dataloader)}]')
        # loss 길이로 꼭 나눠서 평균으로 봐야함!

  0%|          | 0/500 [00:00<?, ?it/s]C:\Users\SeoJeongBin\AppData\Local\Temp\ipykernel_15956\4194624756.py:21: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  output = self.layer_softmax(output)
  0%|          | 1/500 [00:00<06:58,  1.19it/s]

[Epoch : 1/500] [train_loss : 0.2875534819590079] [val_loss : 0.2777359411120415]


 10%|█         | 51/500 [00:32<04:49,  1.55it/s]

[Epoch : 51/500] [train_loss : 0.27525297934944565] [val_loss : 0.27527580223977566]


 20%|██        | 101/500 [01:00<04:04,  1.63it/s]

[Epoch : 101/500] [train_loss : 0.2744537821492633] [val_loss : 0.2753304336220026]


 30%|███       | 151/500 [01:28<03:33,  1.64it/s]

[Epoch : 151/500] [train_loss : 0.27478573773358317] [val_loss : 0.2750057727098465]


 40%|████      | 201/500 [01:56<02:53,  1.72it/s]

[Epoch : 201/500] [train_loss : 0.27522035949939005] [val_loss : 0.275224294513464]


 50%|█████     | 251/500 [02:23<02:23,  1.73it/s]

[Epoch : 251/500] [train_loss : 0.2748985717425475] [val_loss : 0.2751185651868582]


 60%|██████    | 301/500 [02:50<02:03,  1.61it/s]

[Epoch : 301/500] [train_loss : 0.2748947489906002] [val_loss : 0.27517043985426426]


 70%|███████   | 351/500 [03:17<01:28,  1.68it/s]

[Epoch : 351/500] [train_loss : 0.27493114970825816] [val_loss : 0.2752594165503979]


 80%|████████  | 401/500 [03:43<00:56,  1.74it/s]

[Epoch : 401/500] [train_loss : 0.2755530323531177] [val_loss : 0.27519855089485645]


 90%|█████████ | 451/500 [04:09<00:27,  1.77it/s]

[Epoch : 451/500] [train_loss : 0.27510401526012934] [val_loss : 0.27530554309487343]


100%|██████████| 500/500 [04:35<00:00,  1.82it/s]
